run-dist:
	./build/install/app/bin/app $(ARGS)

install-dist:
	./gradlew clean installDist

build:
	./gradlew clean build

test:
	./gradlew clean test

report:
	./gradlew jacocoTestReport

.PHONY: build
